# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20161121_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientomp',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimientomp',
            name='precioUnitario',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='fechaExpedicion',
            field=models.DateField(),
        ),
    ]
