# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-22 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20161121_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='catidadMP',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='costoHora',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='costoUnitarioMP',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='fechaRequerida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='tasaCIF',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nuneroArticulos',
            field=models.IntegerField(),
        ),
    ]
