# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20161121_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldoFinal',
            field=models.FloatField(default=0.0),
        ),
    ]
