# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-22 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20161121_0623'),
        ('main', '0020_auto_20161121_2334'),
    ]

    operations = [
    ]
