# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_20161122_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFinalMP',
            fields=[
                ('idMov', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaFin', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='fechaExpedicion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordendefabricacion',
            name='fechaRequerida',
            field=models.DateField(),
        ),
    ]
