# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20161124_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='prestacion',
        ),
    ]
