# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20161125_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
