# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_empleado_fecha_contratacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puesto',
            old_name='salarioNominalDiario',
            new_name='salarioMensual',
        ),
    ]
