# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161127_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='eficiencia',
            field=models.FloatField(default=0.9),
        ),
    ]
