# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20161127_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMayor',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(max_length=50)),
                ('cuentaLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoDespreciable',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('vidaUtil', models.IntegerField()),
                ('valorRecuperacion', models.FloatField(default=0.0)),
                ('valorActual', models.FloatField(default=0.0, null=True)),
                ('cuentaValorCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta')),
                ('depreciacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Depreciacion')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuentaMayor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CuentaMayor'),
        ),
    ]
